### ISSUE TITLE
意见，更改加载方式，降低版本更新。

### ISSUE THREAD

**Issue by HyhBlazing** [ViCrack/tempermonkey-script#1]
老板，你可以写个json，放在对象存储中，每个月有几G的免费请求流量，去请求你写的这个网址，没必要每天更新哇，本地脚本放几个主流的（保证请求速度和用户无网络的情况），其他用户需求放在json里面，去请求调用。

受不了greasyfork，发了反馈，一下喷子就开始怼了，这是一个很正常的开发逻辑和需求，这网友是对开发有多不了解。

**Comment by ViCrack** [comment]
这个我会考虑一下，不过对象存储我没用过，免费几G的额度用户量大起来后怕迟早也会不够用，而且不排除有没人会恶意请求刷流量。

请求外网地址获取配置更新起来确实方便，但这实际上会有一定的性能时间损失，毕竟每次都要额外多执行一次请求，没能用上tempermonkey的缓存，而且不知道会不会有某些用户认为这在窃取他们的隐私。

你暂时可以先设置下检查更新频率，我后续也会降低发布频率（除非是bug，如果是新增网站就积累几天再发布）。

**Comment by HyhBlazing** [comment]
> 
这才是正常的开发沟通嘛

免费流量，用户多的话，会有这个问题。
恶意请求，限制请求头，一般用户不会模拟请求头去访问。禁止空请求头，再一个是静态文件，不会影响安全。
性能损失，必定会。
窃取隐私，刚看了一个vue国人开发，但是中文文档很差，因为国内的环境太差了，有人用就有人喷。
修改频率，这个没问题。
