### ISSUE TITLE
手机端百度搜索李白、杜甫之类的百度百科问题 打开会跳转到第三方网站熊猫看书 希望作者能解决一下

### ISSUE THREAD

**Issue by YxFeb** [ViCrack/tempermonkey-script#2]
![image](https://user-images.githubusercontent.com/88957527/228213130-e0752020-9b53-4a41-814a-66bace2fa206.png)

**Comment by ViCrack** [comment]
我验证了下，确实存在，但是这种属于百度自己劫持的，不好改。建议不用百度，或者直接搜索“李白 百度百科”

**Comment by ViCrack** [comment]
已修复
