### ISSUE TITLE
移动端百度搜索图片无法显示的问题

### ISSUE THREAD

**Issue by YxFeb** [ViCrack/tempermonkey-script#3]
大佬我又来反馈了 移动端使用百度搜索的时候还有一个问题就是搜索结果页第一页的后半部分图片会加载不出来 其他部分不受影响 不知道能否解决一下
![image](https://user-images.githubusercontent.com/88957527/231691867-fd266dce-f580-4f27-8c16-c1bb0ccf9ead.png)

**Comment by ViCrack** [comment]
没重现出来。
你先试试单独把这个脚本禁用了，然后看看是否正常，排除是这个脚本引起的问题。

**Comment by YxFeb** [comment]
我把代理app以及其他的脚本都关掉后，只留这一个脚本，依然会出现这种情况。把脚本关闭用用其他的脚本，没出现这个问题，有点摸不着头脑了。在 2023年4月13日，17:23，ViCrack ***@***.***> 写道：﻿
没重现出来。
你先试试单独把这个脚本禁用了，然后看看能否用。

**Comment by ViCrack** [comment]
你确认过单独用这个脚本才有这种情况是吧？往往使用中有可能会被其他脚本干扰而出现冲突。
这个脚本你更新到最新试了吗？
你用的是什么浏览器，等我回去测试一下

**Comment by YxFeb** [comment]
对的 单独使用脚本有这种情况 脚本版本是1.98.0 应该是最新版 浏览器是iPhone上的Safari

**Comment by ViCrack** [comment]
你有其他浏览器可以试下吗？我这边没有iPhone Safari，我记得之前也有个人提过Safari下有问题。

我这边没重现出来。
![图片](https://user-images.githubusercontent.com/18179821/231828707-3f17b67f-14c6-4b76-8962-b134522d78f0.png)
![图片](https://user-images.githubusercontent.com/18179821/231828741-591acc4c-0801-4d54-b93a-53d3fd52a5d9.png)


或者你还可以

1、把移动端百度搜索的域名m.baidu.com排除掉（看你的浏览器脚本管理有没有这功能）

2、手动修改js代码排除掉

搜索m.baidu.com，删掉这行看看
![图片](https://user-images.githubusercontent.com/18179821/231832608-1dc93844-2519-4759-b655-390b9e89ffbb.png)

**Comment by YxFeb** [comment]
我这边只有iPhone Safari，我删除掉了m.baidu.con之后搜索正常了，另外我之前反馈的搜索一部分诗人百度百科结果被劫持到熊猫看书貌似也一起解决了
![image](https://user-images.githubusercontent.com/88957527/231836017-000a1dd7-f78a-45d1-94ac-efda152a0b97.png)![image](https://user-images.githubusercontent.com/88957527/231836053-4625fafa-828b-4ad9-9e06-6d9230eeb971.png)

**Comment by ViCrack** [comment]
那好，下个版本我把百度搜索相关的功能先去掉。

不过那块只加了个搜索直链免重定向跳转的功能，按道理不至于会影响到才对。具体的后面再分析。

**Comment by YxFeb** [comment]
好的，感谢！

**Comment by ViCrack** [comment]
已修复，等1.98.1更新，熊猫看书劫持的也是这影响的，原因是获取跳转直链的方式有错误。

https://github.com/ViCrack/tempermonkey-script/commit/b91b503944f375a897ffb1ca2f577b67f4a64d4a
