### ISSUE TITLE
自动展开请求适配theqoo

### ISSUE THREAD

**Issue by alphavvv** [ViCrack/tempermonkey-script#4]
theqoo.net是一个韩网论坛 对kpop或者其它内容感兴趣的人会看 它在帖子内部有个倒着展开的更多回复 看的时候很不方便 楼层多的话要倒着点好几次 希望打开的时候能直接展开全部回复 从第一楼开始
希望作者能够适配theqoo🙏

例如此处有四百楼 为了看到一楼要点三次展开回复
![image](https://github.com/ViCrack/tempermonkey-script/assets/83694637/e08be6bf-055d-4fd7-9664-28e586cf8a7b)

**Comment by ViCrack** [comment]
可以了，直接展开全部回复

**Comment by alphavvv** [comment]
> 可以了，直接展开全部回复
> 
> 
> 
> 

感谢适配🙏请问这个能做到展开全部回复后保持位置在一楼吗 一瞬间弹出很多楼会直接呆在几百楼的位置

**Comment by alphavvv** [comment]
> 可以了，直接展开全部回复
> 
> 
> 
> 

测试中发现存在展开点不干净的情况 有时候会少点两下或者一下 不知道是否跟我使用了沉浸式翻译有关

**Comment by ViCrack** [comment]
> > 可以了，直接展开全部回复
> 
> 测试中发现存在展开点不干净的情况 有时候会少点两下或者一下 不知道是否跟我使用了沉浸式翻译有关

不排除是跟其他扩展脚本冲突影响的

保持位置在一楼这个得等我研究一下

**Comment by alphavvv** [comment]
> > > 可以了，直接展开全部回复
> 
> > 
> 
> > 测试中发现存在展开点不干净的情况 有时候会少点两下或者一下 不知道是否跟我使用了沉浸式翻译有关
> 
> 
> 
> 不排除是跟其他扩展脚本冲突影响的
> 
> 
> 
> 保持位置在一楼这个得等我研究一下
> 
> 

再次感谢适配

**Comment by ViCrack** [comment]
可以了，滚动条保持在开头

**Comment by alphavvv** [comment]
您好 theqoo的自动点击展开目前失效了 使用的脚本管理器为iOS Userscripts以及Stay
请求空闲时能修复🙏 已经排查过其它脚本 只开这个也无法展开 之前是正常工作的 不清楚什么原因失效了

**Comment by ViCrack** [comment]
应该是这个网站最近更新了代码，才导致这个脚本失效了

我已经解决了，你脚本更新之后再试

**Comment by alphavvv** [comment]
生效了 感谢适配
