### ISSUE TITLE
导致 https://m.sohu.com/a/744891649_414734/ 中的图片无法加载 Causing picture in https://m.sohu.com/a/744891649_414734/ couldn't load

### ISSUE THREAD

**Issue by 0x391F** [ViCrack/tempermonkey-script#5]
![Screenshot_20231218_203806](https://github.com/ViCrack/tempermonkey-script/assets/56181919/c626f662-6143-4112-90a5-3ff79bb4b3e3)

**Comment by ViCrack** [comment]
看起来是有这种现象，这个需要时间研究一下

**Comment by ViCrack** [comment]
更新一下，应该是修复了

**Comment by 0x391F** [comment]
修复了，谢谢!
Fixed. Thanks!
