### ISSUE TITLE
B站

### ISSUE THREAD

**Issue by YuhaoLee** [ViCrack/tempermonkey-script#7]
在iPhone Safari里用这个脚本对m.bilibili.com不生效，www.bilibili.com还是会跳转到app。用的是stay运行的脚本

**Comment by YuhaoLee** [comment]
自动展开的脚本

**Comment by ViCrack** [comment]
这个对b站没有做拦截跳转到app的功能，主要是实现简介内容的自动展开

**Comment by YuhaoLee** [comment]
哦哦，我以为说去掉需要打开app的提示是拦截跳转的意思
